Repository buildo/retro, pull requests merged in 2020-04, with the labels that each got.

#219 Update postgresql to 42.2.12
  project/Dependencies.scala
Labels: waiting for merge

#221 Sbt 1.3.9
  ci/pipeline.yml
  enumero/ci/test.yml
  mailo/ci/test.yml
  metarpheus/ci/test.yml
  project/build.properties
  sbt-buildo/ci/compile.yml
  tapiro/ci/test.yml
  tapiro/sbt-tapiro/src/sbt-test/sbt-tapiro/simple/project/build.properties
  toctoc/ci/docker-compose.yml
Labels: WIP

#222 Update tapir-core, tapir-http4s-server, ... to 0.12.28
  project/Dependencies.scala
Labels: waiting for merge

#225 Update munit, munit-scalacheck to 0.7.2
  project/Dependencies.scala
Labels: waiting for merge

#224 Update tapir-core, tapir-http4s-server, ... to 0.13.1
  project/Dependencies.scala
Labels: waiting for merge

#228 Update tapir-core, tapir-http4s-server, ... to 0.13.2
  project/Dependencies.scala
Labels: WIP

#211 Tapiro core tests
  NOTICE.md
  project/Dependencies.scala
  tapiro/ci/test.sh
  tapiro/core/src/main/scala/io/buildo/tapiro/Util.scala
  tapiro/core/src/test/resources/log4j2-test.xml
  tapiro/core/src/test/scala/io/buildo/tapiro/FileLayout.scala
  tapiro/core/src/test/scala/io/buildo/tapiro/TapiroSuite.scala
  tapiro/sbt-tapiro/src/main/scala/io/buildo/tapiro/SbtTapiro.scala
  tapiro/sbt-tapiro/src/sbt-test/sbt-tapiro/simple/build.sbt
  tapiro/sbt-tapiro/src/sbt-test/sbt-tapiro/simple/src/main/resources/logback.xml
Labels: in review

#229 Update scalacheck-magnolia to 0.4.0
  project/Dependencies.scala
Labels: WIP

#230 Update scalameta to 4.3.8
  project/Dependencies.scala
Labels: waiting for merge

#233 Update tapir-core, tapir-http4s-server, ... to 0.14.0
  project/Dependencies.scala
Labels: waiting for merge

#234 Update munit, munit-scalacheck to 0.7.3
  project/Dependencies.scala
Labels: waiting for merge

#212 #203: Wrap POST body as in wiro (closes #203)
  tapiro/core/src/main/scala/io/buildo/tapiro/AkkaHttpMeta.scala
  tapiro/core/src/main/scala/io/buildo/tapiro/Http4sMeta.scala
  tapiro/core/src/main/scala/io/buildo/tapiro/Meta.scala
  tapiro/core/src/main/scala/io/buildo/tapiro/MetarpheusHelper.scala
  tapiro/core/src/main/scala/io/buildo/tapiro/TapirMeta.scala
  tapiro/core/src/main/scala/io/buildo/tapiro/Util.scala
  tapiro/core/src/test/scala/io/buildo/tapiro/TapiroSuite.scala
  tapiro/sbt-tapiro/src/sbt-test/sbt-tapiro/simple/test
Labels: in review, 🐭tapiro

#236 Update scalameta to 4.3.9
  project/Dependencies.scala
Labels: waiting for merge

#238 Allow tapiro to handle Option in Endpoint input
  tapiro/core/src/main/scala/io/buildo/tapiro/Meta.scala
  tapiro/core/src/main/scala/io/buildo/tapiro/TapirMeta.scala
Labels: in review
