Repository buildo/retro, pull requests merged in 2020-02, with the labels that each got.

#131 Update sbt-buildo to 0.11.3
  project/plugins.sbt
Labels: waiting for merge

#147 Update kind-projector to 0.10.3
  sbt-buildo/src/main/scala/buildo/ScalaSettingPlugin.scala
Labels: WIP

#141 Update sbt-mdoc to 1.3.6
  project/plugins.sbt
Labels: waiting for merge

#151 Update sbt-mdoc to 2.1.1
  project/plugins.sbt
Labels: waiting for merge

#150 Update sbt-buildo to 0.11.5
  project/plugins.sbt
Labels: waiting for merge

#139 Update sbt-scalajs, scalajs-compiler to 0.6.32
  project/plugins.sbt
Labels: waiting for merge

#123 Update pprint to 0.5.9
  project/Dependencies.scala
Labels: waiting for merge

#153 Use sbt -batch and enable version: every
  ci/pipeline.yml
  enumero/ci/test.yml
  mailo/ci/test.yml
  metarpheus/ci/test.yml
  sbt-buildo/ci/compile.yml
  tapiro/ci/test.yml
  toctoc/ci/test.sh
Labels: WIP

#116 #115: When output is Unit remove .out(jsonBody[Unit]) (closes #115)
  tapiro/core/src/main/scala/io/buildo/tapiro/Meta.scala
  tapiro/core/src/main/scala/io/buildo/tapiro/TapirMeta.scala
Labels: waiting for merge

#155 #154: Fix tapiro equality error (closes #154)
  tapiro/core/src/main/scala/io/buildo/tapiro/Meta.scala
Labels: waiting for merge

#158 #157: Add autogenerated code disclaimer in tapiro (closes #157)
  tapiro/core/src/main/scala/io/buildo/tapiro/Util.scala
Labels: BE maint, waiting for merge

#159 metarpheus NPM release 2.1.0
  metarpheus/jsFacade/npm/README.md
  metarpheus/jsFacade/npm/package.json
Labels: waiting for merge

#161 #160: Remove cats dependency from SBT plugin (closes #160)
  project/Dependencies.scala
  tapiro/core/src/main/scala/io/buildo/tapiro/Util.scala
  tapiro/sbt-tapiro/src/main/scala/io/buildo/tapiro/SbtTapiro.scala
  tapiro/sbt-tapiro/src/sbt-test/sbt-tapiro/simple/build.sbt
Labels: waiting for merge

#163 #162: Use sbt logging instead of logback (closes #162)
  project/Dependencies.scala
  tapiro/core/src/main/scala/io/buildo/tapiro/Util.scala
  tapiro/sbt-tapiro/src/main/scala/io/buildo/tapiro/SbtTapiro.scala
Labels: waiting for merge

#156 #114: Fix path prefix in both akka-http and http4s (closes #114)
  tapiro/core/src/main/scala/io/buildo/tapiro/AkkaHttpMeta.scala
  tapiro/core/src/main/scala/io/buildo/tapiro/Http4sMeta.scala
  tapiro/core/src/main/scala/io/buildo/tapiro/Util.scala
Labels: 🐭tapiro

#165 Update util-logging to 1.3.3
  project/Dependencies.scala
Labels: WIP

#168 Update scalacheck-magnolia to 0.3.2
  project/Dependencies.scala
Labels: waiting for merge
