Repository buildo/retro, pull requests merged in 2020-03, with the labels that each got.

#173 #172: Tapiro should not generate errorOut if `Unit` return type is used for errors (closes #172)
  tapiro/core/src/main/scala/io/buildo/tapiro/TapirMeta.scala
Labels: waiting for merge

#178 Use PlainCodec for AuthToken
  tapiro/core/src/main/scala/io/buildo/tapiro/Meta.scala
Labels: waiting for merge

#179 Prepend slash to controller name to build a route
  tapiro/core/src/main/scala/io/buildo/tapiro/Http4sMeta.scala
Labels: waiting for merge

#181 Remove tapir endpoint output's need of string codecs
  tapiro/core/src/main/scala/io/buildo/tapiro/Meta.scala
  tapiro/core/src/main/scala/io/buildo/tapiro/TapirMeta.scala
Labels: waiting for merge

#167 #166: Add documentation to tapiro (closes #166)
  build.sbt
  docs/tapiro/installation.md
  docs/tapiro/introduction.md
  docs/tapiro/migrate.md
  docs/tapiro/rpc.md
  project/Dependencies.scala
  website/i18n/en.json
  website/sidebars.json
  website/siteConfig.js
Labels: in review

#182 Update tapir-core, tapir-http4s-server, ... to 0.12.23
  project/Dependencies.scala
Labels: waiting for merge

#187 Update postgresql to 42.2.11
  project/Dependencies.scala
Labels: waiting for merge

#129 Update slick, slick-hikaricp to 3.3.2
  project/Dependencies.scala
Labels: waiting for merge

#135 Update mysql-connector-java to 8.0.19
  project/Dependencies.scala
Labels: waiting for merge

#186 Update jakarta.mail to 1.6.5
  project/Dependencies.scala
Labels: waiting for merge

#191 Update tapir-core, tapir-http4s-server, ... to 0.12.24
  project/Dependencies.scala
Labels: waiting for merge

#193 Update akka-persistence, akka-remote, ... to 2.5.30
  project/Dependencies.scala
Labels: waiting for merge

#195 Update sbt-mdoc to 2.1.3
  project/plugins.sbt
Labels: waiting for merge

#197 Update akka-persistence, akka-remote, ... to 2.6.4
  project/Dependencies.scala
Labels: waiting for merge

#164 Update sbt-scalajs-bundler to 0.17.0
  project/plugins.sbt
Labels: waiting for merge

#202 Update sbt-mdoc to 2.1.4
  project/plugins.sbt
Labels: WIP

#200 Add smoke tests for sbt-tapiro
  tapiro/sbt-tapiro/src/sbt-test/sbt-tapiro/simple/build.sbt
  tapiro/sbt-tapiro/src/sbt-test/sbt-tapiro/simple/curlExpect.sbt
  tapiro/sbt-tapiro/src/sbt-test/sbt-tapiro/simple/project/build.properties
  tapiro/sbt-tapiro/src/sbt-test/sbt-tapiro/simple/project/plugins.sbt
  tapiro/sbt-tapiro/src/sbt-test/sbt-tapiro/simple/src/main/resources/logback.xml
  tapiro/sbt-tapiro/src/sbt-test/sbt-tapiro/simple/src/main/scala/Api.scala
  tapiro/sbt-tapiro/src/sbt-test/sbt-tapiro/simple/src/main/scala/Boot.scala
  tapiro/sbt-tapiro/src/sbt-test/sbt-tapiro/simple/src/main/scala/CustomModel.scala
  tapiro/sbt-tapiro/src/sbt-test/sbt-tapiro/simple/src/main/scala/ExampleController.scala
  tapiro/sbt-tapiro/src/sbt-test/sbt-tapiro/simple/test
  tapiro/sbt-tapiro/src/sbt-test/sbt-tapiro/simple/waitIsUp.sbt
Labels: waiting for merge

#190 Allow tapiro users to provide `statusCodes`
  tapiro/core/src/main/scala/io/buildo/tapiro/AkkaHttpMeta.scala
  tapiro/core/src/main/scala/io/buildo/tapiro/Http4sMeta.scala
  tapiro/core/src/main/scala/io/buildo/tapiro/TapirMeta.scala
Labels: in review

#192 #185: Fix @path in tapiro (closes #185)
  metarpheus/core/src/main/scala/io.buildo.metarpheus/core/extractors/controller.scala
  metarpheus/core/src/main/scala/io.buildo.metarpheus/core/intermediate/intermediate.scala
  metarpheus/core/src/test/scala/io.buildo.metarpheus/core/extractors/ControllerSuite.scala
  tapiro/core/src/main/scala/io/buildo/tapiro/AkkaHttpMeta.scala
  tapiro/core/src/main/scala/io/buildo/tapiro/Http4sMeta.scala
  tapiro/core/src/main/scala/io/buildo/tapiro/Meta.scala
  tapiro/core/src/main/scala/io/buildo/tapiro/TapirMeta.scala
  tapiro/core/src/main/scala/io/buildo/tapiro/Util.scala
  tapiro/sbt-tapiro/src/sbt-test/sbt-tapiro/simple/src/main/scala/Boot.scala
  tapiro/sbt-tapiro/src/sbt-test/sbt-tapiro/simple/test
Labels: in review

#209 #208: Tapiro CI fails because of missing curl (closes #208)
  tapiro/ci/test.sh
  tapiro/ci/test.yml
Labels: in review, 🐭tapiro

#207 #171: Tapiro doesn't know the package of the controller (closes #171)
  metarpheus/core/src/main/scala/io.buildo.metarpheus/core/extractors/controller.scala
  metarpheus/core/src/main/scala/io.buildo.metarpheus/core/extractors/model.scala
  metarpheus/core/src/main/scala/io.buildo.metarpheus/core/extractors/package.scala
  metarpheus/core/src/main/scala/io.buildo.metarpheus/core/intermediate/intermediate.scala
  metarpheus/core/src/test/scala/io.buildo.metarpheus/core/extractors/ApiSuite.scala
  metarpheus/core/src/test/scala/io.buildo.metarpheus/core/extractors/ControllerSuite.scala
  tapiro/core/src/main/scala/io/buildo/tapiro/Util.scala
Labels: waiting for merge, 🐭tapiro

#210 Migrate tests to MUnit + other improvements
  build.sbt
  ci/pipeline.yml
  ci/release.yml
  enumero/ci/test.yml
  enumero/circe/src/test/scala/CirceSupportSpec.scala
  enumero/core/src/test/scala/CaseEnumIndex.scala
  enumero/core/src/test/scala/CaseEnumMacroSpec.scala
  enumero/core/src/test/scala/CaseEnumSpec.scala
  mailo/ci/test.yml
  mailo/src/main/scala/mailo/AtLeastOnceMailo.scala
  mailo/src/main/scala/mailo/Helpers.scala
  mailo/src/main/scala/mailo/data/S3MailData.scala
  mailo/src/main/scala/mailo/http/MailgunClient.scala
  mailo/src/main/scala/mailo/http/SMTPClient.scala
  mailo/src/main/scala/mailo/http/SendinblueClient.scala
  mailo/src/main/scala/mailo/parser/ParserError.scala
  mailo/src/main/scala/mailo/persistence/EmailPersistanceActor.scala
  mailo/src/main/scala/mailo/persistence/SnapshotHelper.scala
  mailo/src/test/resources/reference.conf
  mailo/src/test/scala/mailo/CacheSpec.scala
  mailo/src/test/scala/mailo/FSMailDataSpec.scala
  mailo/src/test/scala/mailo/MailoSMTPSpec.scala
  mailo/src/test/scala/mailo/MailoSpec.scala
  mailo/src/test/scala/mailo/ParserSpec.scala
  mailo/src/test/scala/mailo/PersistenceSpec.scala
  mailo/src/test/scala/mailo/SendinblueSpec.scala
  metarpheus/.drone.yml
  metarpheus/ci/test.yml
  metarpheus/core/src/main/scala/io.buildo.metarpheus/core/intermediate/intermediate.scala
  metarpheus/core/src/test/scala/io.buildo.metarpheus/core/extractors/ApiSuite.scala
  metarpheus/core/src/test/scala/io.buildo.metarpheus/core/extractors/ControllerSuite.scala
  metarpheus/core/src/test/scala/io.buildo.metarpheus/core/extractors/ModelSuite.scala
  metarpheus/jsFacade/src/main/scala/io.buildo.metarpheus/core/JSFacade.scala
  project/Dependencies.scala
  project/build.properties
  project/plugins.sbt
  sbt-buildo/ci/compile.yml
  tapiro/ci/test.yml
  tapiro/sbt-tapiro/src/sbt-test/sbt-tapiro/simple/src/main/resources/log4j2.xml
  toctoc/ci/docker-compose.yml
  toctoc/circe/src/test/scala/io/buildo/toctoc/circe/CirceSupportSpec.scala
  toctoc/core/src/test/scala/io.buildo.toctoc/core/CatsIOSupport.scala
  toctoc/core/src/test/scala/io.buildo.toctoc/core/authentication/TokenBasedRecoveryFlowSpec.scala
  toctoc/docs/concepts/functional-model.md
  toctoc/docs/concepts/login.md
  toctoc/docs/concepts/token.md
  toctoc/docs/installation.md
  toctoc/slickMySql/src/test/scala/io.buildo.toctoc/slick/authentication/test/MySqlSlickLoginAuthenticationDomainFlowSpec.scala
  toctoc/slickPostgreSql/src/test/scala/io.buildo.toctoc/slick/authentication/test/PostgreSqlSlickLoginAuthenticationDomainFlowSpec.scala
Labels: in review

#216 Update tapir-core, tapir-http4s-server, ... to 0.12.26
  project/Dependencies.scala
Labels: waiting for merge

#217 Update scalameta to 4.3.7
  project/Dependencies.scala
Labels: waiting for merge
