Repository buildo/retro, pull requests merged in 2021-01, with the labels that each got.

#331 Update mysql-connector-java to 8.0.23
  project/Dependencies.scala
Labels: waiting for merge

#330 Update akka-persistence, akka-remote, ... to 2.6.11
  project/Dependencies.scala
Labels: waiting for merge

#329 Update akka-http-circe to 1.35.3
  project/Dependencies.scala
Labels: WIP

#328 Update scalacheck-magnolia to 0.6.0
  project/Dependencies.scala
Labels: WIP

#315 Update mdoc to 2.1.5
  project/plugins.sbt
Labels: WIP

#314 Update sbt-assembly to 0.14.10
  build.sbt
Labels: WIP

#311 Update jakarta.mail to 2.0.0
  project/Dependencies.scala
Labels: WIP

#332 Update sbt-assembly to 0.15.0
  build.sbt
Labels: WIP

#306 Update postgresql to 42.2.18
  project/Dependencies.scala
Labels: WIP

#333 Update mdoc, sbt-mdoc to 2.2.14
  project/plugins.sbt
Labels: WIP

#337 fix typo
  docs/toctoc/concepts/functional-model.md
Labels: in review
