Repository buildo/retro, pull requests merged in 2021-05, with the labels that each got.

#371 Update mdoc, sbt-mdoc to 2.2.20
  project/plugins.sbt
Labels: waiting for merge

#376 Update pprint to 0.6.5
  project/Dependencies.scala
Labels: waiting for merge

#378 #375: Port java-time-circe-codecs
  build.sbt
  ci/pipeline.yml
  javaTimeCirceCodecs/README.md
  javaTimeCirceCodecs/ci/test.yml
  javaTimeCirceCodecs/src/main/scala/TimeCirceSupport.scala
  javaTimeCirceCodecs/src/test/scala/FormatterSuite.scala
  project/Dependencies.scala
Labels: waiting for merge

#372 Update postgresql to 42.2.20
  project/Dependencies.scala
Labels: waiting for merge

#366 Update jakarta.mail to 2.0.1
  project/Dependencies.scala
Labels: waiting for merge

#302 Update scalameta to 4.3.24
  project/Dependencies.scala
Labels: waiting for merge

#360 Update akka-http-circe to 1.36.0
  project/Dependencies.scala
Labels: waiting for merge

#358 Update scala-logging to 3.9.3
  project/Dependencies.scala
Labels: waiting for merge

#292 Update unboundid-ldapsdk to 4.0.14
  project/Dependencies.scala
Labels: waiting for merge

#237 Update log4j-api to 2.13.2
  project/Dependencies.scala
Labels: waiting for merge

#251 Update log4j-api to 2.13.3
  project/Dependencies.scala
Labels: waiting for merge

#383 Update scalameta to 4.4.15
  project/Dependencies.scala
Labels: waiting for merge

#382 Update unboundid-ldapsdk to 5.1.4
  project/Dependencies.scala
Labels: waiting for merge

#341 Update awscala to 0.8.5
  project/Dependencies.scala
Labels: waiting for merge

#346 Update akka-http to 10.1.14
  project/Dependencies.scala
Labels: waiting for merge

#385 Update log4j-api to 2.14.1
  project/Dependencies.scala
Labels: waiting for merge

#384 Update akka-http to 10.2.4
  project/Dependencies.scala
Labels: waiting for merge

#369 Update mysql-connector-java to 8.0.24
  project/Dependencies.scala
Labels: waiting for merge

#367 Update akka-persistence, akka-remote, ... to 2.6.14
  project/Dependencies.scala
Labels: waiting for merge

#386 Update munit to 0.7.25
  mailo/src/test/scala/mailo/PersistenceSpec.scala
  metarpheus/core/src/test/scala/io.buildo.metarpheus/core/extractors/ControllerSuite.scala
  project/Dependencies.scala
Labels: WIP

#387 Cross-build for Scala 2.13
  build.sbt
  javaTimeCirceCodecs/ci/test.yml
  mailo/ci/test.yml
  mailo/src/main/scala/mailo/EmailSender.scala
  mailo/src/test/scala/mailo/CacheSpec.scala
  mailo/src/test/scala/mailo/PersistenceSpec.scala
  metarpheus/ci/test.yml
  project/Dependencies.scala
  tapiro/ci/test.sh
  toctoc/ci/test.sh
  toctoc/slickMySql/src/test/scala/io.buildo.toctoc/slick/authentication/test/MySqlSlickLoginAuthenticationDomainFlowSpec.scala
  toctoc/slickPostgreSql/src/test/scala/io.buildo.toctoc/slick/authentication/test/PostgreSqlSlickLoginAuthenticationDomainFlowSpec.scala
Labels: in review

#388 Import wiro
  build.sbt
  ci/pipeline.yml
  docs/wiro/installation.md
  project/Dependencies.scala
  website/sidebars.json
  website/siteConfig.js
  wiro/README.md
  wiro/build.sbt.nope
  wiro/ci/test.yml
  wiro/clientAkkaHttp/src/main/scala/ClientDerivation.scala
  wiro/clientAkkaHttp/src/main/scala/FailSupport.scala
  wiro/clientAkkaHttp/src/main/scala/RPCClient.scala
  wiro/clientAkkaHttp/src/main/scala/RequestBuilder.scala
  wiro/clientAkkaHttp/src/main/scala/package.scala
  wiro/clientAkkaHttp/src/test/scala/AppSpecs.scala
  wiro/clientAkkaHttp/src/test/scala/RPCRouteTest.scala
  wiro/core/src/main/scala/BooleanDecoder.scala
  wiro/core/src/main/scala/MetaDataMacro.scala
  wiro/core/src/main/scala/OptionDecoder.scala
  wiro/core/src/main/scala/PathMacro.scala
  wiro/core/src/main/scala/TypePathMacro.scala
  wiro/core/src/main/scala/annotations.scala
  wiro/core/src/main/scala/models.scala
  wiro/examples/src/main/scala/Doghouse.scala
  wiro/examples/src/main/scala/Users.scala
  wiro/serverAkkaHttp/src/main/resources/reference.conf
  wiro/serverAkkaHttp/src/main/scala/AutowireErrorsSupport.scala
  wiro/serverAkkaHttp/src/main/scala/FailSupport.scala
  wiro/serverAkkaHttp/src/main/scala/RPCController.scala
  wiro/serverAkkaHttp/src/main/scala/RPCRouter.scala
  wiro/serverAkkaHttp/src/main/scala/RPCServer.scala
  wiro/serverAkkaHttp/src/main/scala/RouterDerivation.scala
  wiro/serverAkkaHttp/src/main/scala/package.scala
  wiro/serverAkkaHttp/src/test/scala/AppSpecs.scala
  wiro/serverAkkaHttp/src/test/scala/MUnitRouteTest.scala
  wiro/serverAkkaHttp/src/test/scala/MUnitTestFrameworkInterface.scala
  wiro/serverAkkaHttp/src/test/scala/TestController.scala
Labels: WIP

#393 Update scalameta to 4.4.16
  project/Dependencies.scala
Labels: waiting for merge

#395 sbt 1.5.2 and update docker images to use 2.13.5
  ci/docs.yml
  ci/pipeline.yml
  ci/release.yml
  enumero/ci/test.yml
  javaTimeCirceCodecs/ci/test.yml
  mailo/ci/test.yml
  metarpheus/ci/test.yml
  project/build.properties
  sbt-buildo/ci/compile.yml
  tapiro/ci/test.yml
  tapiro/sbt-tapiro/src/sbt-test/sbt-tapiro/simple/project/build.properties
  toctoc/ci/docker-compose.yml
  wiro/ci/test.yml
Labels: WIP

#398 Add Scala 3 support for sbt-buildo
  sbt-buildo/src/main/scala/buildo/ScalaSettingPlugin.scala
Labels: WIP

#401 Update scalameta to 4.4.17
  project/Dependencies.scala
Labels: waiting for merge

#402 Update kind-projector to 0.12.0
  sbt-buildo/src/main/scala/buildo/ScalaSettingPlugin.scala
Labels: waiting for merge

#403 Update alleycats-core, cats-core to 2.6.1
  project/Dependencies.scala
Labels: WIP

#407 Update mdoc, sbt-mdoc to 2.2.21
  project/plugins.sbt
Labels: waiting for merge

#404 Update munit, munit-scalacheck to 0.7.26
  project/Dependencies.scala
Labels: waiting for merge

#405 Update cats-effect to 2.5.1
  project/Dependencies.scala
Labels: waiting for merge

#400 Update sbt-buildo to 0.11.8
  project/plugins.sbt
Labels: waiting for merge

#410 Update pprint to 0.6.6
  project/Dependencies.scala
Labels: waiting for merge

#406 Update monix-catnap to 3.4.0
  project/Dependencies.scala
Labels: waiting for merge

#412 Fix kind-projector syntax and toctoc-circe tests
  docs/toctoc/guides/token-based-authentication-flow.md
  docs/toctoc/guides/token-based-recovery-flow.md
  project/plugins.sbt
  toctoc/ci/test.sh
  toctoc/circe/src/test/scala/io/buildo/toctoc/circe/CirceSupportSpec.scala
  toctoc/slickMySql/src/main/scala/io.buildo.toctoc/slick/authentication/login/MySqlSlickLoginAuthenticationDomain.scala
  toctoc/slickMySql/src/main/scala/io.buildo.toctoc/slick/authentication/token/MySqlSlickAccessTokenAuthenticationDomain.scala
  toctoc/slickPostgreSql/src/main/scala/io.buildo.toctoc/slick/authentication/login/PostgreSqlSlickLoginAuthenticationDomain.scala
  toctoc/slickPostgreSql/src/main/scala/io.buildo.toctoc/slick/authentication/token/PostgreSqlSlickAccessTokenAuthenticationDomain.scala
Labels: WIP

#409 Remove local dependencies across projects
  build.sbt
  mailo/src/main/scala/mailo/models.scala
  project/Dependencies.scala
Labels: WIP

#247 Update tapir-core, tapir-http4s-server, ... to 0.14.5
  project/Dependencies.scala
Labels: in review

#414 Update kind-projector to 0.13.0
  sbt-buildo/src/main/scala/buildo/ScalaSettingPlugin.scala
Labels: waiting for merge

#416 Update scalameta to 4.4.18
  project/Dependencies.scala
Labels: waiting for merge

#417 Update sbt-buildo to 0.11.10
  project/plugins.sbt
Labels: waiting for merge

#418 Update sbt-git to 1.0.1
  project/plugins.sbt
Labels: waiting for merge

#419 Update circe-core, circe-generic, ... to 0.14.0
  project/Dependencies.scala
Labels: WIP

#420 Update circe-core, circe-generic, ... to 0.14.1
  project/Dependencies.scala
Labels: WIP

#422 Update scalameta to 4.4.19
  project/Dependencies.scala
Labels: waiting for merge

#423 Update scalameta to 4.4.20
  project/Dependencies.scala
Labels: waiting for merge

#424 Update unboundid-ldapsdk to 6.0.0
  project/Dependencies.scala
Labels: WIP
