Repository buildo/retro, pull requests merged in 2021-07, with the labels that each got.

#445 Update sbt-scalajs-crossproject to 1.1.0
  project/plugins.sbt
Labels: WIP

#449 support option in post
  tapiro/core/src/main/scala/io/buildo/tapiro/TapirMeta.scala
Labels: waiting for merge

#451 Update scala3-library to 3.0.1
  build.sbt
Labels: waiting for merge

#452 Update tapir-core, tapir-http4s-server, ... to 0.18.0
  project/Dependencies.scala
Labels: waiting for merge

#444 Update munit, munit-scalacheck to 0.7.27
  project/Dependencies.scala
Labels: waiting for merge

#454 Upgrade to Scala 2.13.6 and fix CI release
  build.sbt
  ci/docs.yml
  ci/pipeline.yml
  ci/release.yml
  enumero/ci/test.yml
  javaTimeCirceCodecs/ci/test.yml
  mailo/ci/test.yml
  metarpheus/ci/test.yml
  sbt-buildo/ci/compile.yml
  tapiro/ci/test.yml
  toctoc/ci/docker-compose.yml
  wiro/ci/test.yml
Labels: in review

#456 Update scalameta to 4.4.24
  project/Dependencies.scala
Labels: WIP
